### ISSUE TITLE
[BUG] Styles seems outdated with recent steam versions

### ISSUE THREAD

**Issue by MartinSkovsen** [AndroidHell/metro-solarized#1]
Is there any chance you would update this repo to be compatible with newer steam versions?

**Comment by AndroidHell** [comment]
Tbh, I forgot I even had this on here. No, I won't be updating it for the current version of Steam. Especially after the UI overhaul when Valve changed how a a lot of stuff works. Sorry!

**Comment by MartinSkovsen** [comment]
That's totally fair. Thanks for you reply. I really liked your solarized dark metro skin, so I may see, if I can pick it up myself. If I get the time, I'll make a PR (ref to another repo). Best of luck to you :)

**Comment by AndroidHell** [comment]
You can go ahead and just take the files if you want. No need to do a pull request lol. I'm not so worried about getting credit or anything. 

After digging through it though, I found that my custom colors are located in resources/styles/steam.styles

`steam.styles
{
  include "custom.styles"
  include "colors.styles"
	include "controls.styles"
	include "settings.styles"
	include "caption.styles"
	colors
	{
        Header_Dark="0 43 54 255"
        ClientBG="7 54 66 255"
        FrameBorder="0 43 54 255"
	ScrollBar.Wide "16"`

I just copied that over to version 4.4 and it does still work but with how much Valve has changed with Steam UI, it doesn't really look good. It just changes the top bar. But it's a start. You will probably have to grab the latest Metro theme and start there, I assume.

Something I have noticed with the latest theme is that the upper left controls overlap due to alignment issues, so I would like to see that fixed. The devs also seemed ot have not even added the View menu item to the top bar. It's sort of a functional mess but if you wanted to explore it, I think that would be really cool. Good luck.
